

let y = prompt();

if(y=="yemen"){
    let x = prompt();
   switch (x) {
       case "sana'a":
           document.write('you are from sana')
           break;
           case "adan":
            document.write('you are from adan')
           break;
           case "taiz":
            document.write('you are from taiz')
            break;
      
   }
}else if(y=="egypt"){
    let z = prompt();
    switch (z) {
        case "alexandria":
            document.write('you are from alexandria')
            break;
            case "cairo":
             document.write('you are from cairo')
            break;
            case "sphinx":
             document.write('you are from sphinx')
             break;
       
    }



}else{
    document.write('error')
}














































